const safe=[{sev:'LOW',rule:'SR-META-004',title:'Tool description lacks ownership metadata',confidence:'78%',state:'OBSERVE'},{sev:'INFO',rule:'SR-DEP-001',title:'Dependency manifest captured for baseline',confidence:'100%',state:'SEALED'}];
const vulnerable=[{sev:'CRITICAL',rule:'SR-PI-002',title:'Secret exfiltration instruction detected',confidence:'97%',state:'BLOCK'},{sev:'HIGH',rule:'SR-PI-001',title:'Embedded instruction override in tool metadata',confidence:'94%',state:'BLOCK'},{sev:'HIGH',rule:'SR-EXEC-001',title:'Dynamic shell execution primitive',confidence:'90%',state:'REVIEW'},{sev:'MEDIUM',rule:'SR-SUP-001',title:'Floating package execution',confidence:'82%',state:'REVIEW'}];
const rows=document.querySelector('#rows'),events=document.querySelector('#events');
function render(items){rows.innerHTML=items.map(x=>`<div class="finding-row"><span class="sev ${x.sev.toLowerCase()}">${x.sev}</span><span><b>${x.rule}</b><small>${x.title}</small></span><span class="confidence">${x.confidence}</span><span class="state">${x.state}</span></div>`).join('')}
function renderEvents(label='Baseline loaded'){const now=new Date().toISOString().slice(11,19);events.innerHTML=[[now,label,'Evidence ledger updated with deterministic fingerprints.'],['T-00:02','Manifest inventory complete','Tools, prompts and resources normalized.'],['T-00:04','Policy boundary verified','Offline demonstration; zero external contact.']].map(x=>`<div class="event"><time>${x[0]}</time><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}
render(safe);renderEvents();
document.querySelector('#scan').addEventListener('click',event=>{const button=event.currentTarget;button.classList.add('running');button.innerHTML='<span>◆</span> SCANNING ATTACK SURFACE';setTimeout(()=>{const risky=document.querySelector('#profile').selectedIndex===1;render(risky?vulnerable:safe);document.querySelector('#score').textContent=risky?'18':'94';const verdict=document.querySelector('#verdict');verdict.textContent=risky?'BLOCK':'PASS';verdict.className=risky?'danger':'pass';document.querySelector('#count').textContent=(risky?'05':'03')+' EVENTS';renderEvents(risky?'Critical control triggered':'Scan completed');button.classList.remove('running');button.innerHTML='<span>▶</span> INITIATE SCAN'},1100)});
document.querySelectorAll('.engines button').forEach(button=>button.addEventListener('click',()=>button.classList.toggle('on')));
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelector(button.dataset.view==='overview'?'.hero':'.findings').scrollIntoView({behavior:'smooth'})}));
